export const products = [
  {
    id: 1,
    images: [
      "https://www.beautyhaul.com/assets/uploads/products/thumbs/800x800/Whitelab_Brightening_Face_Serum.jpg",
      "https://images.soco.id/ae85e1c5-64bc-4db3-b26c-796109ea03f8-.jpg",
    ],
    name: "Brightening Facial Serum",
    discount: 25,
    price: 200000,
    priceDiscount: 150000,
    discountPercent: 30,
    rating: 4.8,
    sold: 1250,
    needPrescription: false,
    details: {
      description: "Serum pencerah wajah untuk membantu meratakan warna kulit.",
      indikasi: "Mencerahkan kulit kusam dan mengurangi noda hitam.",
      komposisi: "Niacinamide, Vitamin C, Hyaluronic Acid",
      dosis: "Gunakan 1–2 kali sehari.",
      aturanPakai: "Oleskan pada wajah setelah toner sebelum moisturizer.",
      kontraIndikasi: "Hindari penggunaan pada kulit yang iritasi.",
      golongan: "Kosmetik",
      perhatian: "Hentikan pemakaian bila terjadi iritasi.",
      kemasan: "Botol 30ml",
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review: "Produk bagus dan cepat sampai!",
        images: ["https://picsum.photos/200/200?1"],
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Lumayan bagus, sesuai deskripsi.",
        images: [],
      },
    ],
  },
  {
    id: 2,
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-8i92XV1P0WzdVbdDlw3wkI9YtDWXc7Y2mg&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-8i92XV1P0WzdVbdDlw3wkI9YtDWXc7Y2mg&s",
    ],
    name: "Acne Control Night Cream",
    discount: 15,
    price: 180000,
    priceDiscount: 153000,
    discountPercent: 30,
    rating: 4.5,
    sold: 980,
    needPrescription: false,
    details: {
      description: "Krim malam untuk merawat kulit berjerawat.",
      indikasi: "Membantu meredakan jerawat dan mengontrol minyak.",
      komposisi: "Salicylic Acid, Tea Tree Oil",
      dosis: "Gunakan sekali sehari sebelum tidur.",
      aturanPakai: "Oleskan tipis di area wajah setelah membersihkan kulit.",
      kontraIndikasi: "Tidak dianjurkan untuk kulit sangat sensitif.",
      golongan: "Kosmetik Medis",
      perhatian: "Hindari area mata.",
      kemasan: "Tube 20g",
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review: "Produk bagus dan cepat sampai!",
        images: ["https://picsum.photos/200/200?1"],
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Lumayan bagus, sesuai deskripsi.",
        images: [],
      },
    ],
  },
  {
    id: 3,
     images: [
        "https://down-id.img.susercontent.com/file/id-11134207-7r98q-lyocdqgihne506",
        "https://down-id.img.susercontent.com/file/id-11134207-7r98q-lyocdqgihne506",
      ],
    name: "Tretinoin 0.05% Cream",
    discount: 30,
    price: 250000,
    priceDiscount: 175000,
    discountPercent: 30,
    rating: 4.9,
    sold: 600,
    needPrescription: true,
    details: {
      description:
        "Krim tretinoin untuk mengatasi jerawat dan regenerasi kulit.",
      indikasi: "Mengurangi jerawat dan kerutan halus.",
      komposisi: "Tretinoin 0.05%",
      dosis: "Gunakan pada malam hari.",
      aturanPakai: "Oleskan tipis pada area wajah yang bermasalah.",
      kontraIndikasi: "Tidak untuk ibu hamil atau menyusui.",
      golongan: "Obat Keras",
      perhatian: "Gunakan sunscreen setiap pagi.",
      kemasan: "Tube 15g",
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review: "Produk bagus dan cepat sampai!",
        images: ["https://picsum.photos/200/200?1"],
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Lumayan bagus, sesuai deskripsi.",
        images: [],
      },
    ],
  },
  {
    id: 4,
   images: [
        "https://guardianindonesia.co.id/media/catalog/product/3/1/3119434.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=",
        "https://guardianindonesia.co.id/media/catalog/product/3/1/3119434.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=",
      ],
    name: "Hydrating Cleanser",
    discount: 10,
    price: 120000,
    priceDiscount: 108000,
    discountPercent: 30,
    rating: 4.7,
    sold: 2100,
    needPrescription: false,
    details: {
      description:
        "Pembersih wajah lembut yang menjaga kelembapan kulit sepanjang hari.",
      indikasi: "Membersihkan wajah tanpa membuat kulit kering.",
      komposisi: "Ceramide, Hyaluronic Acid, Glycerin",
      dosis: "Gunakan 2 kali sehari.",
      aturanPakai:
        "Usapkan ke wajah basah, pijat lembut 20 detik kemudian bilas.",
      kontraIndikasi: "Tidak ada.",
      golongan: "Kosmetik",
      perhatian: "Hanya untuk pemakaian luar.",
      kemasan: "Botol 100ml",
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review: "Produk bagus dan cepat sampai!",
        images: ["https://picsum.photos/200/200?1"],
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Lumayan bagus, sesuai deskripsi.",
        images: [],
      },
    ],
  },
  {
    id: 5,
     images: [
        "https://img.lazcdn.com/g/p/0e3dc6d0fcb1036134bc7c4089f20bc8.jpg_720x720q80.jpg",
        "https://img.lazcdn.com/g/p/0e3dc6d0fcb1036134bc7c4089f20bc8.jpg_720x720q80.jpg",
      ],
    name: "Anti-Aging Retinol Serum",
    discount: 40,
    price: 300000,
    priceDiscount: 180000,
    discountPercent: 30,
    rating: 4.9,
    sold: 1540,
    needPrescription: true,
    details: {
      description:
        "Serum anti-aging dengan retinol untuk meningkatkan regenerasi kulit.",
      indikasi: "Mengurangi kerutan dan meningkatkan elastisitas kulit.",
      komposisi: "Retinol 1%, Peptide Complex",
      dosis: "Gunakan malam hari.",
      aturanPakai: "Oleskan tipis dan hindari area mata.",
      kontraIndikasi: "Tidak untuk ibu hamil.",
      golongan: "Obat Keras",
      perhatian: "Gunakan sunscreen di pagi hari.",
      kemasan: "Botol 30ml",
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review: "Produk bagus dan cepat sampai!",
        images: ["https://picsum.photos/200/200?1"],
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Lumayan bagus, sesuai deskripsi.",
        images: [],
      },
    ],
  },
];
