export const treatment = [
  {
    id: 1,
    name: "Filler Neuramis Black 1 cc",
    discount: 25,
    price: 200000,
    priceDiscount: 150000,
    discountPercent: 30,
    duration: 30,
    details: {
      description:
        "Filler Neuramis Black 1 cc adalah filler revolusioner dengan teknologi mutakhir untuk perawatan estetik yang memberikan hasil optimal dalam memperbaiki kontur wajah dan menghidrasi kulit.",
      composition: [
        "Hyaluronic Acid (HA) Termodifikasi - Konsentrasi tinggi untuk hidrasi maksimal",
        "BDDE Cross-linked Technology - Struktur stabil dan tahan lama",
        "Buffer Solution - Formula aman dan nyaman",
      ],
      benefits: [
        "Hidrasi Intensif - Mengembalikan kelembaban kulit hingga lapisan terdalam",
        "Volumizing Optimal - Membentuk kontur wajah yang natural dan proporsional",
        "Elastisitas Kulit - Meningkatkan kekencangan dan kelenturan kulit",
        "Fine Lines Reduction - Mengurangi kerutan halus dan garis penuaan",
        "Biocompatible - Kompatibel dengan jaringan tubuh, risiko alergi minimal",
      ],
      indications: [
        "Perbaikan kontur wajah (pipi, dagu, rahang)",
        "Pengisian area mata cekung",
        "Koreksi garis nasolabial",
        "Enhancement bibir yang natural",
        "Rejuvenasi kulit secara menyeluruh",
      ],
      duration: "12-18 bulan",
      safety: [
        "Tersertifikasi Kementerian Kesehatan",
        "Approved BPOM RI",
        "Standar produksi GMP dan ISO",
        "Non-animal sourced",
        "Bebas dari bahan berbahaya",
      ],
      contraindications: [
        "Wanita hamil dan menyusui",
        "Riwayat alergi terhadap hyaluronic acid",
        "Kondisi autoimun aktif",
        "Infeksi kulit di area treatment",
        "Riwayat keloid",
      ],
      aftercare: [
        "Hindari paparan sinar matahari langsung 48 jam pertama",
        "Jangan memijat area injeksi kecuali diinstruksikan dokter",
        "Hindari sauna dan berenang selama 3 hari",
        "Gunakan sunscreen secara rutin",
        "Ikuti jadwal kontrol dengan dokter",
      ],
    },
    location: {
      name: "Klinik Estetik Jakarta Selatan",
      image: "https://sumia.co.id/images/treatment/laser-glowing-24.jpeg",
      city: "Jakarta Selatan",
      address: "Jl. Kemang Raya No. 12, Kemang",
      rating: 0,
      distance: 2.5,
      operatingHours: {
        weekdays: "08:00 - 21:00",
        weekend: "09:00 - 18:00",
      },
      facilities: [
        "Parkir Luas",
        "AC",
        "WiFi",
        "Ruang Tunggu Nyaman",
        "Konsultasi Gratis",
      ],
      imagelocation: [
        { id: 1, image_url: "https://sumia.co.id/images/treatment/laser-glowing-24.jpeg" },
      ],
    },
    reviews: [
      {
        name: "Andi Wijaya",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=12",
        review:
          "Hasilnya natural banget! Dokter yang menangani juga sangat profesional.",
        images: ["https://picsum.photos/200/200?1"],
        date: "2024-01-15",
      },
      {
        name: "Sinta Dewi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=6",
        review: "Prosedurnya cepat dan nyaman. Hasilnya sesuai ekspektasi.",
        images: [],
        date: "2024-01-10",
      },
      {
        name: "Rina Melati",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=8",
        review: "Kulit wajah jadi lebih kencang dan fresh. Recommended banget!",
        images: [
          "https://picsum.photos/200/200?2",
          "https://picsum.photos/200/200?3",
        ],
        date: "2024-01-08",
      },
    ],
    images: [
      "https://picsum.photos/300/300?product=1",
      "https://picsum.photos/300/300?product=2",
      "https://picsum.photos/300/300?product=3",
      "https://picsum.photos/300/300?product=4",
    ],
    category: "Filler & Volumizing",
    rating: 4.7,
    sold: 124,
    needPrescription: true,
    doctorNote:
      "Perlu konsultasi terlebih dahulu dengan dokter estetik untuk menentukan dosis dan teknik yang tepat.",
  },
  {
    id: 2,
    name: "Botulinum Toxin Type A",
    discount: 20,
    price: 300000,
    priceDiscount: 240000,
    discountPercent: 20,
    duration: 45,
    details: {
      description:
        "Treatment botox untuk mengurangi kerutan dinamis dan keringat berlebih dengan hasil natural.",
      composition: [
        "Botulinum Toxin Type A - 100 units",
        "Human Albumin",
        "Saline Solution",
      ],
      benefits: [
        "Mengurangi kerutan dahi dan mata",
        "Mengatasi keringat berlebih",
        "Relaksasi otot wajah",
        "Preventive aging treatment",
      ],
      indications: [
        "Crow's feet (kerutan mata)",
        "Frown lines (kerutan dahi)",
        "Hyperhidrosis (keringat berlebih)",
        "Masseter reduction",
      ],
      duration: "4-6 bulan",
      safety: ["FDA Approved", "BPOM Certified", "Clinical tested"],
    },
    location: {
      name: "Beauty Clinic Bandung",
      image: "https://picsum.photos/300/200?clinic=2",
      city: "Bandung",
      address: "Jl. Dago No. 45, Dago",
      rating: 4.6,
      distance: 1.8,
      operatingHours: {
        weekdays: "09:00 - 20:00",
        weekend: "10:00 - 17:00",
      },
      facilities: ["Parkir Valet", "Ruang VIP", "Cafe", "Free Consultation"],
      imagelocation: [
        { id: 1, image_url: "https://www.shutterstock.com/image-photo/beautician-skin-doctor-injecting-filler-600nw-2625030081.jpg" },
      ],
    },
    reviews: [
      {
        name: "Diana Putri",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=5",
        review: "Kerutan di dahi hilang dan hasilnya sangat natural!",
        images: ["https://picsum.photos/200/200?5"],
        date: "2024-01-12",
      },
    ],
    images: [
      "https://picsum.photos/300/300?botox=1",
      "https://picsum.photos/300/300?botox=2",
    ],
    category: "Botox & Injectables",
    rating: 4.8,
    sold: 89,
    needPrescription: true,
    doctorNote: "Hasil maksimal terlihat dalam 7-14 hari setelah treatment.",
  },
  {
    id: 3,
    name: "Laser Hair Removal Full Face",
    discount: 15,
    price: 450000,
    priceDiscount: 382500,
    discountPercent: 15,
    duration: 60,
    details: {
      description:
        "Treatment penghilangan bulu wajah permanen dengan teknologi laser terbaru untuk kulit sensitif.",
      composition: [
        "Diode Laser Technology",
        "Cooling System",
        "Medical Grade Gel",
      ],
      benefits: [
        "Hasil permanen setelah 6-8 sesi",
        "Cocok untuk kulit sensitif",
        "Minimal rasa sakit",
        "Tidak merusak kulit",
      ],
      indications: [
        "Bulu wajah berlebih",
        "Wanita dengan PCOS",
        "Rambut halus di area wajah",
        "Persiapan makeup permanen",
      ],
      duration: "Permanen",
      safety: ["FDA Cleared", "Dermatologist Tested", "Hypoallergenic"],
    },
    location: {
      name: "Derma Clinic Surabaya",
      image: "https://picsum.photos/300/200?clinic=3",
      city: "Surabaya",
      address: "Jl. Tunjungan Plaza No. 88",
      rating: 4.9,
      distance: 3.2,
      operatingHours: {
        weekdays: "08:30 - 19:30",
        weekend: "09:00 - 16:00",
      },
      facilities: [
        "Underground Parking",
        "Lounge Area",
        "Private Room",
        "Doctor On Call",
      ],
      imagelocation: [
        { id: 1, image_url: "https://www.shutterstock.com/image-photo/laser-hair-removal-on-womans-260nw-2148450221.jpg" },
      ],
    },
    reviews: [
      {
        name: "Maya Sari",
        rating: 5,
        avatar: "https://i.pravatar.cc/150?img=9",
        review: "Sudah 3 sesi dan hasilnya amazing! Bulu berkurang drastis.",
        images: ["https://picsum.photos/200/200?6"],
        date: "2024-01-14",
      },
    ],
    images: [
      "https://picsum.photos/300/300?laser=1",
      "https://picsum.photos/300/300?laser=2",
      "https://picsum.photos/300/300?laser=3",
    ],
    category: "Laser Treatment",
    rating: 4.7,
    sold: 67,
    needPrescription: false,
    doctorNote:
      "Disarankan 6-8 sesi dengan interval 4-6 minggu untuk hasil optimal.",
  },
  {
    id: 4,
    name: "Chemical Peel Gold Series",
    discount: 30,
    price: 350000,
    priceDiscount: 245000,
    discountPercent: 30,
    duration: 45,
    details: {
      description:
        "Treatment pengelupasan kulit kimia dengan formula gold series untuk mengatasi hiperpigmentasi dan bekas jerawat.",
      composition: [
        "Glycolic Acid 30%",
        "Salicylic Acid 20%",
        "Vitamin C Complex",
        "Soothing Agents",
      ],
      benefits: [
        "Mengurangi hiperpigmentasi",
        "Memudarkan bekas jerawat",
        "Mencerahkan kulit",
        "Mengecilkan pori-pori",
      ],
      indications: [
        "Bekas jerawat membandel",
        "Flek hitam dan sun spot",
        "Kulit kusam",
        "Texture kulit tidak rata",
      ],
      duration: "6-12 bulan",
      safety: ["Dermatologist Approved", "pH Balanced", "Non-comedogenic"],
    },
    location: {
      name: "Skin Care Center Bali",
      image: "https://picsum.photos/300/200?clinic=4",
      city: "Denpasar",
      address: "Jl. Sunset Road No. 123, Kuta",
      rating: 4.7,
      distance: 5.1,
      operatingHours: {
        weekdays: "10:00 - 19:00",
        weekend: "10:00 - 16:00",
      },
      facilities: ["Beach View", "Spa Services", "Organic Cafe", "Free Pickup"],
      imagelocation: [
        { id: 1, image_url: "https://picsum.photos/300/300?random=11" },
      ],
    },
    reviews: [
      {
        name: "Putu Widi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=15",
        review: "Kulit jadi lebih cerah dan bekas jerawat memudar.",
        images: ["https://picsum.photos/200/200?7"],
        date: "2024-01-11",
      },
    ],
    images: [
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT49iqAO8TSNaVswK7h6r7QNYqtpsLGtyf-Q&s",
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQT49iqAO8TSNaVswK7h6r7QNYqtpsLGtyf-Q&s",
    ],
    category: "Skin Rejuvenation",
    rating: 4.5,
    sold: 93,
    needPrescription: false,
    doctorNote:
      "Hindari paparan matahari langsung selama 1 minggu setelah treatment.",
  },
  {
    id: 5,
    name: "Chemical Peel Gold Series",
    discount: 30,
    price: 350000,
    priceDiscount: 245000,
    discountPercent: 30,
    duration: 45,
    details: {
      description:
        "Treatment pengelupasan kulit kimia dengan formula gold series untuk mengatasi hiperpigmentasi dan bekas jerawat.",
      composition: [
        "Glycolic Acid 30%",
        "Salicylic Acid 20%",
        "Vitamin C Complex",
        "Soothing Agents",
      ],
      benefits: [
        "Mengurangi hiperpigmentasi",
        "Memudarkan bekas jerawat",
        "Mencerahkan kulit",
        "Mengecilkan pori-pori",
      ],
      indications: [
        "Bekas jerawat membandel",
        "Flek hitam dan sun spot",
        "Kulit kusam",
        "Texture kulit tidak rata",
      ],
      duration: "6-12 bulan",
      safety: ["Dermatologist Approved", "pH Balanced", "Non-comedogenic"],
    },
    location: {
      name: "Skin Care Center Bali",
      image: "https://picsum.photos/300/200?clinic=4",
      city: "Denpasar",
      address: "Jl. Sunset Road No. 123, Kuta",
      rating: 4.7,
      distance: 5.1,
      operatingHours: {
        weekdays: "10:00 - 19:00",
        weekend: "10:00 - 16:00",
      },
      facilities: ["Beach View", "Spa Services", "Organic Cafe", "Free Pickup"],
      imagelocation: [
        { id: 1, image_url: "https://www.shutterstock.com/image-photo/cosmetologist-cleaning-face-beautiful-european-600nw-2496076115.jpg" },
      ],
    },
    reviews: [
      {
        name: "Putu Widi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=15",
        review: "Kulit jadi lebih cerah dan bekas jerawat memudar.",
        images: ["https://picsum.photos/200/200?7"],
        date: "2024-01-11",
      },
    ],
    images: [
      "https://picsum.photos/300/300?peel=1",
      "https://picsum.photos/300/300?peel=2",
    ],
    category: "Skin Rejuvenation",
    rating: 4.5,
    sold: 93,
    needPrescription: false,
    doctorNote:
      "Hindari paparan matahari langsung selama 1 minggu setelah treatment.",
  },
  {
    id: 6,
    name: "Chemical Peel Gold Series",
    discount: 30,
    price: 350000,
    priceDiscount: 245000,
    discountPercent: 30,
    duration: 45,
    details: {
      description:
        "Treatment pengelupasan kulit kimia dengan formula gold series untuk mengatasi hiperpigmentasi dan bekas jerawat.",
      composition: [
        "Glycolic Acid 30%",
        "Salicylic Acid 20%",
        "Vitamin C Complex",
        "Soothing Agents",
      ],
      benefits: [
        "Mengurangi hiperpigmentasi",
        "Memudarkan bekas jerawat",
        "Mencerahkan kulit",
        "Mengecilkan pori-pori",
      ],
      indications: [
        "Bekas jerawat membandel",
        "Flek hitam dan sun spot",
        "Kulit kusam",
        "Texture kulit tidak rata",
      ],
      duration: "6-12 bulan",
      safety: ["Dermatologist Approved", "pH Balanced", "Non-comedogenic"],
    },
    location: {
      name: "Skin Care Center Bali",
      image: "https://picsum.photos/300/200?clinic=4",
      city: "Denpasar",
      address: "Jl. Sunset Road No. 123, Kuta",
      rating: 4.7,
      distance: 5.1,
      operatingHours: {
        weekdays: "10:00 - 19:00",
        weekend: "10:00 - 16:00",
      },
      facilities: ["Beach View", "Spa Services", "Organic Cafe", "Free Pickup"],
      imagelocation: [
        { id: 1, image_url: "https://www.shutterstock.com/image-photo/laser-hair-removal-on-womans-260nw-2148450221.jpg" },
      ],
    },
    reviews: [
      {
        name: "Putu Widi",
        rating: 4,
        avatar: "https://i.pravatar.cc/150?img=15",
        review: "Kulit jadi lebih cerah dan bekas jerawat memudar.",
        images: ["https://picsum.photos/200/200?7"],
        date: "2024-01-11",
      },
    ],
    images: [
      "https://picsum.photos/300/300?peel=1",
      "https://picsum.photos/300/300?peel=2",
    ],
    category: "Skin Rejuvenation",
    rating: 4.5,
    sold: 93,
    needPrescription: false,
    doctorNote:
      "Hindari paparan matahari langsung selama 1 minggu setelah treatment.",
  },
];
